# Generated by Django 5.2.5 on 2025-09-26 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('skills', models.TextField(blank=True, default='None', help_text='Comma-separated list of required skills')),
                ('location', models.CharField(default='ATL, GA, US', help_text='City, State, Country', max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True)),
                ('visa_sponsorship', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
