# Generated by Django 5.0 on 2025-09-26 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='remote_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], default='on-site', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='visa_sponsorship',
            field=models.BooleanField(default=False),
        ),
    ]
