# Generated by Django 5.0 on 2025-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offered'), ('closed', 'Closed')], default='applied', max_length=50),
        ),
    ]
