# Generated by Django 5.2.5 on 2025-10-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0004_jobapplication_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
