# Generated by Django 5.2.5 on 2025-10-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='email',
            field=models.CharField(default='', max_length=300),
        ),
    ]
