# Generated by Django 5.0 on 2025-09-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recruiter_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='education',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='headline',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='links',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='skills',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='work_experience',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
