# Generated by Django 5.0 on 2025-11-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_savedfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='visibility_settins',
            field=models.JSONField(default=dict),
        ),
    ]
