# Generated by Django 5.0 on 2025-09-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seeker_education_seeker_headline_seeker_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='education',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='headline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='links',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='skills',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='work_experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
