# Generated by Django 5.0 on 2025-11-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seekerprofile_visibility_settins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekerprofile',
            old_name='visibility_settins',
            new_name='visibility_settings',
        ),
    ]
