# Generated by Django 5.0 on 2025-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_visibility_settins_seekerprofile_visibility_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
